# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalDocsMcp < Formula
  desc "MCP server for local documentation access"
  homepage "https://github.com/umputun/local-docs-mcp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.1.0/local-docs-mcp_v0.1.0_macos_x86_64.tar.gz"
      sha256 "2ffd5ad5209a289cd872b84996b055f318bd230c19d34ce5aca07451a64e6631"

      def install
        bin.install "local-docs-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.1.0/local-docs-mcp_v0.1.0_macos_arm64.tar.gz"
      sha256 "177bcc32ecff6117b673d05c3ccd2e1bfa26c81b07117557531844c70fd182c3"

      def install
        bin.install "local-docs-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.1.0/local-docs-mcp_v0.1.0_linux_x86_64.tar.gz"
      sha256 "b7f9d2efe5ddf19219edf8babaf1cbff1a87ff08e28c2e59648a1aecb56b37e0"

      def install
        bin.install "local-docs-mcp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.1.0/local-docs-mcp_v0.1.0_linux_arm.tar.gz"
      sha256 "fce895192262ceeebbc9e5885b7c396e3838d3f058e71f7a8bde24dd8b4f7da9"

      def install
        bin.install "local-docs-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.1.0/local-docs-mcp_v0.1.0_linux_arm64.tar.gz"
      sha256 "021fcea5ae4bffd15ab2fce3720f3b55da16a5a01ebdccf0eafa4d04acb5f4bf"

      def install
        bin.install "local-docs-mcp"
      end
    end
  end
end
