# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpt < Formula
  desc "MPT is a command-line utility that sends prompts to multiple AI language model providers in parallel and combines the results"
  homepage "https://github.com/umputun/mpt"
  version "0.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/mpt/releases/download/v0.6.0/mpt_v0.6.0_macos_x86_64.tar.gz"
      sha256 "56ba9e239a599930a0ee75999c23746e206c07bf3c6d2d8553030cba14ab7463"

      def install
        bin.install "mpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/mpt/releases/download/v0.6.0/mpt_v0.6.0_macos_arm64.tar.gz"
      sha256 "ba4185500277dc1756a997d631fe3fd840027f3a16d0df0d4548ac6a43259668"

      def install
        bin.install "mpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/mpt/releases/download/v0.6.0/mpt_v0.6.0_linux_x86_64.tar.gz"
      sha256 "649553e6505e8ffc21c0a158a1e641024381e0b8491a24b3a9fb4ad91db44f99"

      def install
        bin.install "mpt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/mpt/releases/download/v0.6.0/mpt_v0.6.0_linux_arm.tar.gz"
      sha256 "58b2b5d6374f67c5a5c3f69ad77978adb00957d28a6b67187b54da7bc886f96c"

      def install
        bin.install "mpt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/mpt/releases/download/v0.6.0/mpt_v0.6.0_linux_arm64.tar.gz"
      sha256 "c7b929b12fbc067d53ccc3f0e4b77463d12d90ebcf357b475fd81ce829af3b88"

      def install
        bin.install "mpt"
      end
    end
  end
end
