# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mpt < Formula
  desc "MPT is a command-line utility that sends prompts to multiple AI language model providers in parallel and combines the results"
  homepage "https://github.com/umputun/mpt"
  version "0.10.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/mpt/releases/download/v0.10.1/mpt_v0.10.1_macos_x86_64.tar.gz"
      sha256 "5601df482cbf2939b42a1dd89095f086c70afda91e7c641036acf0cdc494153f"

      def install
        bin.install "mpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/mpt/releases/download/v0.10.1/mpt_v0.10.1_macos_arm64.tar.gz"
      sha256 "c0dcbb1fc50c37338022c8105d61911a47adbb6d3835a26c5b2f9c00c7e66273"

      def install
        bin.install "mpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/mpt/releases/download/v0.10.1/mpt_v0.10.1_linux_x86_64.tar.gz"
      sha256 "f702000869cc15bdffb6d971ffe2e6dcf4da438f7bd3b76d81b450512f4e21da"

      def install
        bin.install "mpt"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/mpt/releases/download/v0.10.1/mpt_v0.10.1_linux_arm.tar.gz"
      sha256 "f64b6fae20cb9add5827db02a5649b27709b68c96dcd48c3409a90c2f2867b9e"

      def install
        bin.install "mpt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/mpt/releases/download/v0.10.1/mpt_v0.10.1_linux_arm64.tar.gz"
      sha256 "4abcc1b296d874ca322d1b786cd063046a72d21f71e334a2653ef2491521429c"

      def install
        bin.install "mpt"
      end
    end
  end
end
