# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProxyCron < Formula
  desc "proxy-cron is a simple HTTP proxy server designed to handle requests based on crontab-like scheduling."
  homepage "https://proxy-cron.umputun.dev/"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.2.0/proxy-cron_v0.2.0_macos_x86_64.tar.gz"
      sha256 "1111c49c5fc3c641dabeefd4cb8afc5aecf9621edb0c646f905b4dd3c1fde865"

      def install
        bin.install "proxy-cron"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.2.0/proxy-cron_v0.2.0_macos_arm64.tar.gz"
      sha256 "e834ecaa6ed535d5343aaf1c97261c8f4840e1e4a3e5b780db8810467883b0c2"

      def install
        bin.install "proxy-cron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.2.0/proxy-cron_v0.2.0_linux_arm.tar.gz"
      sha256 "153fb8f7da0690ec2d4e5e9cb3d618b9a0ea49c3d003b73c5de05ba15f21ee1b"

      def install
        bin.install "proxy-cron"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.2.0/proxy-cron_v0.2.0_linux_arm64.tar.gz"
      sha256 "060301db2654096670e1ecb2661d1201a80366cb1d38466ecaf09814ab8835b5"

      def install
        bin.install "proxy-cron"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.2.0/proxy-cron_v0.2.0_linux_x86_64.tar.gz"
      sha256 "ed605addd5dc262fe37777f1f180554eab5de16a8a97e434fd3530bc518520d6"

      def install
        bin.install "proxy-cron"
      end
    end
  end
end
