# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ProxyCron < Formula
  desc "proxy-cron is a simple HTTP proxy server designed to handle requests based on crontab-like scheduling."
  homepage "https://proxy-cron.umputun.dev/"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.1.3/proxy-cron_v0.1.3_macos_arm64.tar.gz"
      sha256 "ce680f4593c384af631a07db1da1adb05ea5ec6058c59f0e0bf0e4c152b85ece"

      def install
        bin.install "proxy-cron"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.1.3/proxy-cron_v0.1.3_macos_x86_64.tar.gz"
      sha256 "10941209ae9c2e7d1756ee82a2a634ad11a9ae9a4c9828c888a76342a228239b"

      def install
        bin.install "proxy-cron"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.1.3/proxy-cron_v0.1.3_linux_arm64.tar.gz"
      sha256 "70f4d7a5c6e4fc3069a20be9b8fb579d690c88783d52ad4e84cc2dc5dae042f6"

      def install
        bin.install "proxy-cron"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.1.3/proxy-cron_v0.1.3_linux_arm.tar.gz"
      sha256 "185d47342d1e071b1724780cb3adbb5fcafde9d94f90a237188cf06c360dd667"

      def install
        bin.install "proxy-cron"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umputun/proxy-cron/releases/download/v0.1.3/proxy-cron_v0.1.3_linux_x86_64.tar.gz"
      sha256 "14a5f70618c8b6bbdf5719ba785f5fca09d2d3e85be67c9c020c0bf070284099"

      def install
        bin.install "proxy-cron"
      end
    end
  end
end
