# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reproxy < Formula
  desc "Simple edge HTTP(s) reverse proxy with automatic SSL"
  homepage "https://reproxy.io"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_macos_amd64.tar.gz"
      sha256 "9ab3acf9c3e3bb3a5d3d84088257a824aa4c52e2b2476779b1cff430a963a3a1"

      def install
        bin.install "reproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_macos_arm64.tar.gz"
      sha256 "c98ba67c59f52933357704af0907cd59d4424447b472d3f1cd5e5d628cd87531"

      def install
        bin.install "reproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_linux_amd64.tar.gz"
      sha256 "4abab7aea7628e40a261091f5250a5fa5c1a0d5a9181158e2a94b0ae198b0132"

      def install
        bin.install "reproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_linux_arm64.tar.gz"
      sha256 "c288fa0d1ff6f24b8654f73ec8c2576d4f9ace972ba13111ded017193a5dea3f"

      def install
        bin.install "reproxy"
      end
    end
  end
end
