# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reproxy < Formula
  desc "Simple edge HTTP(s) reverse proxy with automatic SSL"
  homepage "https://reproxy.io"
  version "1.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_macos_amd64.tar.gz"
      sha256 "e00813e8be240bd87d52d8587d40757d13cc0f7d148de1416e43b082b9898780"

      def install
        bin.install "reproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_macos_arm64.tar.gz"
      sha256 "d24d09f9fc57c8b1489b5518bd3ca204da8d47f6735ed2621de39694173fba96"

      def install
        bin.install "reproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_linux_amd64.tar.gz"
      sha256 "bdac385e191871b631feb4712fc4b7e420fefaa98ac5273c4bc679d95aeb6fd7"

      def install
        bin.install "reproxy"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_linux_arm.tar.gz"
      sha256 "89d2523b83a94e073a5d6f8e10e91c6f28632a59d86f96a0539462f2a88dc752"

      def install
        bin.install "reproxy"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/reproxy/releases/download/v1.4.0/reproxy_v1.4.0_linux_arm64.tar.gz"
      sha256 "75aa51e7640730a0d2ec15230a9292ddc2ab8f894bcd1ede57a740ae99a5635e"

      def install
        bin.install "reproxy"
      end
    end
  end
end
