# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secrets < Formula
  desc "Self-hosted service for sharing encrypted secrets with one-time access"
  homepage "https://github.com/umputun/secrets"
  version "2.2.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/secrets/releases/download/v2.2.3/secrets_v2.2.3_macos_x86_64.tar.gz"
      sha256 "061e01f1f06747c1c36efd6243cd258a7ae4e4ae934142731283488b20d93669"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/secrets/releases/download/v2.2.3/secrets_v2.2.3_macos_arm64.tar.gz"
      sha256 "1c993b4066f1ade19e90d3f1bc7d378caa25ba23fd07764680bbdc9e35f38c76"

      def install
        bin.install "secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/secrets/releases/download/v2.2.3/secrets_v2.2.3_linux_x86_64.tar.gz"
      sha256 "b9a93c63a1fe9002362750b4bef408d03deae12b84a1814212c27ad0d5bff3ee"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/secrets/releases/download/v2.2.3/secrets_v2.2.3_linux_arm.tar.gz"
      sha256 "c3581c8576aa2a54308b9b5664e60261a991c8653a00bd1c3922cb7854a60ce2"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/secrets/releases/download/v2.2.3/secrets_v2.2.3_linux_arm64.tar.gz"
      sha256 "419b69898efdc89ad173561b7fae1a542307ea31a137de99c5b6166ca00f3636"

      def install
        bin.install "secrets"
      end
    end
  end
end
