# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secrets < Formula
  desc "Self-hosted service for sharing encrypted secrets with one-time access"
  homepage "https://github.com/umputun/secrets"
  version "1.9.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/secrets/releases/download/v1.9.2/secrets_v1.9.2_macos_x86_64.tar.gz"
      sha256 "d413028ed2836d1a6f50f803ee9517ddee56d4bbecbd90f6c57dd52626d25137"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/secrets/releases/download/v1.9.2/secrets_v1.9.2_macos_arm64.tar.gz"
      sha256 "077849395d580f7a033494b94ce53079302bca7757e93729c6c88d21e99c3816"

      def install
        bin.install "secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/secrets/releases/download/v1.9.2/secrets_v1.9.2_linux_x86_64.tar.gz"
      sha256 "3dd1cad729b5a3c5b0d399b95df80c9f5d4fd3d305265b786632991efea98134"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/secrets/releases/download/v1.9.2/secrets_v1.9.2_linux_arm.tar.gz"
      sha256 "0d55be1bdcecd15c75aa71dc4f4dbd4092a9913e0ab993f802d46b52d43e4a21"

      def install
        bin.install "secrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/secrets/releases/download/v1.9.2/secrets_v1.9.2_linux_arm64.tar.gz"
      sha256 "a7d56b4b0b113b6f82c4522f97b48d7df59f0604fefd907cb5a4238d9730907b"

      def install
        bin.install "secrets"
      end
    end
  end
end
