# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spot < Formula
  desc "Spot (aka simplotask) is a powerful and easy-to-use tool for effortless deployment and configuration management."
  homepage "https://simplotask.com/"
  version "1.17.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/umputun/spot/releases/download/v1.17.1/spot_v1.17.1_macos_x86_64.tar.gz"
      sha256 "a52a8fce36f19ff350b5dea682fbb664b4cca46df8cc5af0591849a1c0c44fdd"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    on_arm do
      url "https://github.com/umputun/spot/releases/download/v1.17.1/spot_v1.17.1_macos_arm64.tar.gz"
      sha256 "ff6a103b3dbe87c027adecb93579806ffbf1968d0079eea1e94726e1fab83e33"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/umputun/spot/releases/download/v1.17.1/spot_v1.17.1_linux_x86_64.tar.gz"
        sha256 "0bf067055df84f6839ba1e9bf83092ff6d2176383afccbc4179628bd2a6e0d8a"

        def install
          bin.install "spot"
          bin.install "spot-secrets"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/umputun/spot/releases/download/v1.17.1/spot_v1.17.1_linux_arm.tar.gz"
        sha256 "7ddc34eca7bac8035c3e8fa27f72416a7db9f3da657a830840d58fb5571a3ef3"

        def install
          bin.install "spot"
          bin.install "spot-secrets"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/umputun/spot/releases/download/v1.17.1/spot_v1.17.1_linux_arm64.tar.gz"
        sha256 "b33ba68f593965770d86a4d80a7931be0fbbce6b7fe36c55f37a4cc9eb82bfd4"

        def install
          bin.install "spot"
          bin.install "spot-secrets"
        end
      end
    end
  end
end
