# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spot < Formula
  desc "Spot (aka simplotask) is a powerful and easy-to-use tool for effortless deployment and configuration management."
  homepage "https://simplotask.com/"
  version "1.12.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/spot/releases/download/v1.12.0/spot_v1.12.0_macos_x86_64.tar.gz"
      sha256 "7bd83ae5b2d70feb408089372b2c9273c297ff42f73d6e3a02c177312c8e8095"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/spot/releases/download/v1.12.0/spot_v1.12.0_macos_arm64.tar.gz"
      sha256 "b5d7cd40c935b061681a5d7224f81c1734786ba1df9f0dc613afccd9322fab71"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.12.0/spot_v1.12.0_linux_arm.tar.gz"
      sha256 "a6d5029d6acb80b2f470d86e3d8612584b8494effcd2544b2df74601ef2bbbb2"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.12.0/spot_v1.12.0_linux_arm64.tar.gz"
      sha256 "ecd5e7a3befaf0825f3fdf37db6ceeef44a670f8469c0f2eb96a7fac58fb6f5d"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umputun/spot/releases/download/v1.12.0/spot_v1.12.0_linux_x86_64.tar.gz"
      sha256 "a9dfa8977d2152eba00daad2e76ecab1752595d2a308367fd1ea1a371bde5c92"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
  end
end
