# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Lightweight key-value configuration service for centralized config management"
  homepage "https://github.com/umputun/stash"
  version "0.13.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.13.3/stash_v0.13.3_macos_x86_64.tar.gz"
      sha256 "2315a8e425441b03da5c81c8bb0274ac6f4c476d845e94d78248ebb2dab85d51"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/stash/releases/download/v0.13.3/stash_v0.13.3_macos_arm64.tar.gz"
      sha256 "572f443accce420af81d9d767b5fb55bbd04ade8711969b2cfb36e1609dbb7f0"

      def install
        bin.install "stash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.13.3/stash_v0.13.3_linux_x86_64.tar.gz"
      sha256 "1955b04c5d4794063ac4b8c063394c69390dc98634844f80b029700161f848e3"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.13.3/stash_v0.13.3_linux_arm.tar.gz"
      sha256 "7af0514f4f1d21bd39dc19786499ffc3fae1737cebbf3c6402beacff181c2a93"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.13.3/stash_v0.13.3_linux_arm64.tar.gz"
      sha256 "427ae207906af9d5c04099d2f24deaca65091c18d2e3bb5c3b62064eb4f3809c"

      def install
        bin.install "stash"
      end
    end
  end
end
