# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Lightweight key-value configuration service for centralized config management"
  homepage "https://github.com/umputun/stash"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.3.1/stash_v0.3.1_macos_x86_64.tar.gz"
      sha256 "c0458713338c423e1fbfc52f502ce62f132bc179a91798b77c91c8dd2e438a35"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/stash/releases/download/v0.3.1/stash_v0.3.1_macos_arm64.tar.gz"
      sha256 "f5f4be2e29c0178e705aa70ec6b5a9a2965a272cf8a1edb09341c437be3f7919"

      def install
        bin.install "stash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.3.1/stash_v0.3.1_linux_x86_64.tar.gz"
      sha256 "d2b23ed4f526eddc856eea788f5d6880664bab866069f14192ef0ee6e478180f"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.3.1/stash_v0.3.1_linux_arm.tar.gz"
      sha256 "9e7b0498f7c723cc2f709f812814b04bbc9f4879b66614aa11ab57072b461a1b"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.3.1/stash_v0.3.1_linux_arm64.tar.gz"
      sha256 "c28f462eac7522b4c122e01fc5da2fb75c31a0ed5185005bb70a4e8e061f0034"

      def install
        bin.install "stash"
      end
    end
  end
end
