# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Lightweight key-value configuration service for centralized config management"
  homepage "https://github.com/umputun/stash"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.1.1/stash_v0.1.1_macos_x86_64.tar.gz"
      sha256 "cea3675c88bb5431c7d7aaacf74d9b465070a9e29a4ba7846e036b06526c91a2"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/stash/releases/download/v0.1.1/stash_v0.1.1_macos_arm64.tar.gz"
      sha256 "9137acb8453078b0457b79638d36ebb2a491a9a455261c0bd14fd5ed6587e7a8"

      def install
        bin.install "stash"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.1.1/stash_v0.1.1_linux_x86_64.tar.gz"
      sha256 "da41f98bd37c8a481b89205145b19a28fcb84748172c98c03331af80c16e078c"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.1.1/stash_v0.1.1_linux_arm.tar.gz"
      sha256 "3a2d9e14abc7f320ad7c4eb0300c57836c764419026b5bc2a46652b30c83545d"

      def install
        bin.install "stash"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.1.1/stash_v0.1.1_linux_arm64.tar.gz"
      sha256 "b0b1208521e48b834d059aef9346848851d3e122590b62ed65b96bee6fce6001"

      def install
        bin.install "stash"
      end
    end
  end
end
