# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SysAgent < Formula
  desc "SysAgent is a simple service reporting server status via HTTP GET request. It is useful for monitoring and debugging purposes, but usually used as a part of some other monitoring system collecting data and serving it."
  homepage "https://sys-agent.umputun.dev"
  version "1.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/sys-agent/releases/download/v1.3.2/sys-agent_v1.3.2_macos_x86_64.tar.gz"
      sha256 "db2b2ef45a3933b6b6aed3b960e8025b3e9e340ac533ad304c8187cb559e61e6"

      def install
        bin.install "sys-agent"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/sys-agent/releases/download/v1.3.2/sys-agent_v1.3.2_macos_arm64.tar.gz"
      sha256 "f39aef72c2dd3ccbb047aee9e870d6d7a6b5caff58c0888aa250b00e204ecc14"

      def install
        bin.install "sys-agent"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/sys-agent/releases/download/v1.3.2/sys-agent_v1.3.2_linux_arm.tar.gz"
      sha256 "914fb49c660e8876e4b21f343716f642b207ce27c5c8b7314858d6102fd548ec"

      def install
        bin.install "sys-agent"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umputun/sys-agent/releases/download/v1.3.2/sys-agent_v1.3.2_linux_x86_64.tar.gz"
      sha256 "a4ea441047699eec7eca494e777726032745d10c55884f45dae069d21d7f59db"

      def install
        bin.install "sys-agent"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/sys-agent/releases/download/v1.3.2/sys-agent_v1.3.2_linux_arm64.tar.gz"
      sha256 "8661072e644c696bb6c89d5cf6bf73cfbc4014294350e79bbe4e4d5446b886d4"

      def install
        bin.install "sys-agent"
      end
    end
  end
end
