# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnfuckAiComments < Formula
  desc "unfuck-ai-comments is a tool that converts all comments inside Go functions to lowercase"
  homepage "https://unfuck-ai-comments.umputun.dev"
  version "0.8.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.7/unfuck-ai-comments_v0.8.7_macos_x86_64.tar.gz"
      sha256 "317c3ae5961032f3793c5aaaa8d13a0b4dc7db8b08f92f063ad9fed5ed569395"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.7/unfuck-ai-comments_v0.8.7_macos_arm64.tar.gz"
      sha256 "c2d9f1814a5f729ffb94c167cb6d956255c6c7b89b1dafd1e1ccadd534bedebe"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.7/unfuck-ai-comments_v0.8.7_linux_x86_64.tar.gz"
      sha256 "6543ba418066aa3211868be6ab4ca8156c2d693b1ff0bc2d9754dc032d4d11d2"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.7/unfuck-ai-comments_v0.8.7_linux_arm.tar.gz"
      sha256 "8171fb073463492f8e3d10ef78dbc9f4366852bee6c8d81e9a1700d8e7a6fff2"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.7/unfuck-ai-comments_v0.8.7_linux_arm64.tar.gz"
      sha256 "ac5eb8b3383ee56ab49747f17d2c3fad8c50b19f4196f4fe930b289a7141aaec"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
  end
end
