# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnfuckAiComments < Formula
  desc "unfuck-ai-comments is a tool that converts all comments inside Go functions to lowercase"
  homepage "https://unfuck-ai-comments.umputun.dev"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.7.0/unfuck-ai-comments_v0.7.0_macos_x86_64.tar.gz"
      sha256 "f6d9e4a5a27221aac5426109dce7e0b26ecf1f6e711b144d669ba5eac1cb1079"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.7.0/unfuck-ai-comments_v0.7.0_macos_arm64.tar.gz"
      sha256 "67cb70ede44d48c43f64a1bc0eb0cb8e5102a3aaeda45bab8e7a749ed2686c78"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.7.0/unfuck-ai-comments_v0.7.0_linux_x86_64.tar.gz"
      sha256 "b3bbeb476567697a510ea86578f8381dabf24364385e714f08cec8c16f4943dd"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.7.0/unfuck-ai-comments_v0.7.0_linux_arm.tar.gz"
      sha256 "7206eff5101c6dc9e744820f98f4b58482d4cbbfa9d3d4cf2dba0a118e0a5afc"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.7.0/unfuck-ai-comments_v0.7.0_linux_arm64.tar.gz"
      sha256 "99983319a8ea328cde1f92df34094a74954ceff85ea5ac2f1de6856b8de601e1"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
  end
end
