# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnfuckAiComments < Formula
  desc "unfuck-ai-comments is a tool that converts all comments inside Go functions to lowercase"
  homepage "https://unfuck-ai-comments.umputun.dev"
  version "0.8.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.4/unfuck-ai-comments_v0.8.4_macos_x86_64.tar.gz"
      sha256 "972e693d6747b01c6fcf69656ba676eac0f91549684addb83c48e1f26557e224"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.4/unfuck-ai-comments_v0.8.4_macos_arm64.tar.gz"
      sha256 "fd4bec989d718f5602e88aab043fc129fb4a3b518d2042f8b8694e838e597e00"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.4/unfuck-ai-comments_v0.8.4_linux_x86_64.tar.gz"
      sha256 "1aeb7ce60638d7a0a0126932491dc3fe250bf65de5220f2322784086ae9aff77"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.4/unfuck-ai-comments_v0.8.4_linux_arm.tar.gz"
      sha256 "b85b1ee74179c2cf15c9d1fe97d2b0a399a1fc805f7b4d40b2850342a03fd576"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.8.4/unfuck-ai-comments_v0.8.4_linux_arm64.tar.gz"
      sha256 "8fff83be47dc08728d1183f0667860dbd6925572370ce0fbb28e3b01566b9335"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
  end
end
