# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weblist < Formula
  desc "weblist is a self-hosted web service to access local files and folders"
  homepage "https://weblist.umputun.dev"
  version "0.14.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.14.2/weblist_v0.14.2_macos_x86_64.tar.gz"
      sha256 "7cf43b0b94d1c31ba3e106633589e1463a671fd2cfadc459646e4d362a02db36"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/weblist/releases/download/v0.14.2/weblist_v0.14.2_macos_arm64.tar.gz"
      sha256 "3f01ad7ea401dbaa92c6fab278f136942099aac7d03ca137c40226841f38e363"

      def install
        bin.install "weblist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.14.2/weblist_v0.14.2_linux_x86_64.tar.gz"
      sha256 "e7c881e6033c5b56130b9c2e83173344676b00e72d757c5d7695ec619308cef3"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.14.2/weblist_v0.14.2_linux_arm.tar.gz"
      sha256 "24d7c602a9549b62a1776e6fcc6418a8ad0b74951a1b7ffd4637a01def7ffc13"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.14.2/weblist_v0.14.2_linux_arm64.tar.gz"
      sha256 "660d327ca11c7af6133debaeb14f6a68aece68eb2ab72ecf0a52292ced172981"

      def install
        bin.install "weblist"
      end
    end
  end
end
