# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weblist < Formula
  desc "weblist is a self-hosted web service to access local files and folders"
  homepage "https://weblist.umputun.dev"
  version "0.9.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.9.0/weblist_v0.9.0_macos_x86_64.tar.gz"
      sha256 "3ff58e572f1b84202e7d5cc686371154135f0161ba0871671a68bbfb3e3c2cf0"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/weblist/releases/download/v0.9.0/weblist_v0.9.0_macos_arm64.tar.gz"
      sha256 "0517d0690eb806d88b4572ae669d4435cd4a7d3623f03681bfa458ce91689207"

      def install
        bin.install "weblist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.9.0/weblist_v0.9.0_linux_x86_64.tar.gz"
      sha256 "7709760d3b31e4d33467b3fd7b75b8ae66da7bc46cb888b0747ae2ca778b6cb9"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.9.0/weblist_v0.9.0_linux_arm.tar.gz"
      sha256 "5267c0323ebeef7dfb6e2129beec4756187b080f1d97209c6de5d621b9486d99"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.9.0/weblist_v0.9.0_linux_arm64.tar.gz"
      sha256 "ef0a5e08529f8dca0b4de5c317d73f7bb5a1db7d7464a1646da072ce58f9ef41"

      def install
        bin.install "weblist"
      end
    end
  end
end
