# This file was generated by GoReleaser. DO NOT EDIT.
cask "fya" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "4850bbcbdf3528fffa09793bc66fe4cfee755e95e05510ade3cfa9a1bc6c3f95"
      url "https://github.com/umputun/fya/releases/download/v#{version}/fya_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "f9f0fda1cd564023ef49b62db06ff18d3169b0b614d4b629ac17780c751752c4"
      url "https://github.com/umputun/fya/releases/download/v#{version}/fya_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0ff38556ade5692e7d0915bf5c4aba90ac7b2465ca4a027ebaeca21a71376dfd"
      url "https://github.com/umputun/fya/releases/download/v#{version}/fya_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8b46e325a6fc4caed4e5f8cc7764cbc30759cf4d74bba6018df22b8312412a0c"
      url "https://github.com/umputun/fya/releases/download/v#{version}/fya_#{version}_linux_arm64.tar.gz"
    end
  end

  name "fya"
  desc "Claude Code print-mode wrapper backed by an interactive PTY session"
  homepage "https://github.com/umputun/fya"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fya"

  # No zap stanza required

end
