# This file was generated by GoReleaser. DO NOT EDIT.
cask "revmux" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "c01ec57b6504ece3703a722fdb20109ab2757b86b93cff8967f00d03e7cef957"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "65b63fed40bc22f331811e595b2a856d6fd2ed8bd66fde1d8960d19387147d71"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0e4f5c35add5401ac48ec6b072e9582397869bba214d8d3f0cc2f75345a9edef"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "91b1bbadb373a0e31cab823f5db076fee9f68613b7cc583d0d8ff33f40559059"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_linux_arm64.tar.gz"
    end
  end

  name "revmux"
  desc "Supervised multi-agent code review with parallel claude and codex subprocesses"
  homepage "https://github.com/umputun/revmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "revmux"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/revmux"]
    end
  end

  # No zap stanza required

end
