# This file was generated by GoReleaser. DO NOT EDIT.
cask "revmux" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/revmux"]
    end
  end

  version "0.2.5"

  on_macos do
    on_arm do
      sha256 "57f8f4754a48020ff962e57deb22d036840e777be0bfeb18103cd03a582f8e0f"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ef2aa1576a3102102996b59482e2d487cb13e987a5fb50882f14684d9f180ab6"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2d2216183f96aef2c6e39d7c6afff614d3ba10f979a6c049fe094f78d28da112"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8081ed5c207b9c57e92deac3375acc0e6cd57c82f86a7681a97a6b51ece2c46f"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "revmux"
  desc "Supervised multi-agent code review with parallel claude and codex subprocesses"
  homepage "https://github.com/umputun/revmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "revmux"

  # No zap stanza required
end
