# This file was generated by GoReleaser. DO NOT EDIT.
cask "revmux" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr",
          args: ["-dr", "com.apple.quarantine", "{{staged_path}}/revmux"]
    end
  end

  version "0.2.3"

  on_macos do
    on_arm do
      sha256 "65a7ccb60e0dcefd09cdc36730da9d624538040af2fffbaf044f95d983b110a1"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "48658e021da00659b3d74807e879ef78ffab087b455a5dadc91a7e2ecfad02e8"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "78eeb89615c9be6c744ee81d542e91584c3c2a412fdcced677f73e625a4d5d98"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "9c4cc2095d8e70e4358b76246b486c721f392fba65a74aee12c0d01e17dc8ff7"
      url "https://github.com/umputun/revmux/releases/download/v#{version}/revmux_#{version}_linux_amd64.tar.gz"
    end
  end

  name "revmux"
  desc "Supervised multi-agent code review with parallel claude and codex subprocesses"
  homepage "https://github.com/umputun/revmux"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "revmux"

  # No zap stanza required
end
