# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronn < Formula
  desc "Cronn is a crontab jobs scheduler with some nice extras. It allows to run commands on specified time intervals and can be used directly as well as from a container."
  homepage "https://cronn.umputun.dev"
  version "1.12.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/cronn/releases/download/v1.12.3/cronn_v1.12.3_macos_x86_64.tar.gz"
      sha256 "ae182ac5c2b162801520e7a7afdaad23f1f7f449755ad4aa0dfbf3f9d4c6ba32"

      def install
        bin.install "cronn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/cronn/releases/download/v1.12.3/cronn_v1.12.3_macos_arm64.tar.gz"
      sha256 "109859ff3561e313c71e5aa588c62116a9e679247ccafa09f08ec77660ec62ea"

      def install
        bin.install "cronn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/cronn/releases/download/v1.12.3/cronn_v1.12.3_linux_x86_64.tar.gz"
      sha256 "34eb35b84e623bbfb70615aab8ca114c19d2a5992bbcfcffe744dfd07a10335c"

      def install
        bin.install "cronn"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/cronn/releases/download/v1.12.3/cronn_v1.12.3_linux_arm.tar.gz"
      sha256 "723abff5a0caa66b7ec0255bbb043c16256c1c14f5c40efe30fff933fd826def"

      def install
        bin.install "cronn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/cronn/releases/download/v1.12.3/cronn_v1.12.3_linux_arm64.tar.gz"
      sha256 "cbe82d6b56083937d0d00dda747e018d5f4d0dab2b086a69fc29d24f12cdf418"

      def install
        bin.install "cronn"
      end
    end
  end
end
