# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cronn < Formula
  desc "Cronn is a crontab jobs scheduler with some nice extras. It allows to run commands on specified time intervals and can be used directly as well as from a container."
  homepage "https://cronn.umputun.dev"
  version "1.14.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/cronn/releases/download/v1.14.0/cronn_v1.14.0_macos_x86_64.tar.gz"
      sha256 "a29ff000a666a2af63d9050a92e32370d31e33c3900fdda4d8bb5c1d6538ed5f"

      def install
        bin.install "cronn"
        bash_completion.install "completions/cronn.bash" => "cronn"
        zsh_completion.install "completions/cronn.zsh" => "_cronn"
        fish_completion.install "completions/cronn.fish" => "cronn.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/cronn/releases/download/v1.14.0/cronn_v1.14.0_macos_arm64.tar.gz"
      sha256 "febba1b933195fd87ea5ae0ac4aff9101ae00b8de1a3ca4e47e8d0757d76911f"

      def install
        bin.install "cronn"
        bash_completion.install "completions/cronn.bash" => "cronn"
        zsh_completion.install "completions/cronn.zsh" => "_cronn"
        fish_completion.install "completions/cronn.fish" => "cronn.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/cronn/releases/download/v1.14.0/cronn_v1.14.0_linux_x86_64.tar.gz"
      sha256 "16c81e57bd492e616fbf0db5b808838a6f3dff75feb47e2461b72d64a68438d4"

      def install
        bin.install "cronn"
        bash_completion.install "completions/cronn.bash" => "cronn"
        zsh_completion.install "completions/cronn.zsh" => "_cronn"
        fish_completion.install "completions/cronn.fish" => "cronn.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/cronn/releases/download/v1.14.0/cronn_v1.14.0_linux_arm.tar.gz"
      sha256 "bb65803ca8c95c835d6d98715d856f565de7852c201de6b6e31864ea9d56a1c0"

      def install
        bin.install "cronn"
        bash_completion.install "completions/cronn.bash" => "cronn"
        zsh_completion.install "completions/cronn.zsh" => "_cronn"
        fish_completion.install "completions/cronn.fish" => "cronn.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/cronn/releases/download/v1.14.0/cronn_v1.14.0_linux_arm64.tar.gz"
      sha256 "a3b4ba8f9e3f25facc4656850c5a5e08604d1c4c398258180f79d906d6ce74e5"

      def install
        bin.install "cronn"
        bash_completion.install "completions/cronn.bash" => "cronn"
        zsh_completion.install "completions/cronn.zsh" => "_cronn"
        fish_completion.install "completions/cronn.fish" => "cronn.fish"
      end
    end
  end
end
