# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class EchoHttp < Formula
  desc "Responds with json-formatted echo of the incoming request and with a predefined message."
  homepage "https://echo-http.umputun.dev/"
  version "1.0.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/echo-http/releases/download/v1.0.0/echo-http_v1.0.0_macos_x86_64.tar.gz"
      sha256 "905469084b53255b9ac1878e04a2275c669053316827fd238911f36653265603"

      def install
        bin.install "echo-http"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/echo-http/releases/download/v1.0.0/echo-http_v1.0.0_macos_arm64.tar.gz"
      sha256 "5c27476650ef14caf0851874f88fae0d1367d456c447f6eff16fc23753e90c0e"

      def install
        bin.install "echo-http"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/echo-http/releases/download/v1.0.0/echo-http_v1.0.0_linux_arm.tar.gz"
      sha256 "8fb2e19645554edf1438219af26ee98fd4dbe5aae83ad9683383cbb092efc0b2"

      def install
        bin.install "echo-http"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/echo-http/releases/download/v1.0.0/echo-http_v1.0.0_linux_arm64.tar.gz"
      sha256 "cba3d6ac09fb75e19af4d2327b157eb9d9b41fcb6c3bf2871d39d60cf5e59a98"

      def install
        bin.install "echo-http"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/umputun/echo-http/releases/download/v1.0.0/echo-http_v1.0.0_linux_x86_64.tar.gz"
      sha256 "f4144678f387c20d7337720ac750fa07aa60ad38b49a0627a8394a743d5c2d16"

      def install
        bin.install "echo-http"
      end
    end
  end
end
