# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fya < Formula
  desc "Claude Code print-mode wrapper backed by an interactive PTY session"
  homepage "https://github.com/umputun/fya"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/fya/releases/download/v0.3.0/fya_0.3.0_darwin_amd64.tar.gz"
      sha256 "21160fc7f92473b62d2c8af2dfb4e1d33dcea8b81a2c2e6b7ffa50f7ec4c025c"

      define_method(:install) do
        bin.install "fya"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/fya/releases/download/v0.3.0/fya_0.3.0_darwin_arm64.tar.gz"
      sha256 "b5916c6648142cb0b9aee293b18929ba2a218e015bec2cce17a6151bb2ec2086"

      define_method(:install) do
        bin.install "fya"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/fya/releases/download/v0.3.0/fya_0.3.0_linux_amd64.tar.gz"
      sha256 "ae7798642219ce5fdd63e83a1db5669897f115e9d3477d631772e90f3edacaf4"
      define_method(:install) do
        bin.install "fya"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/fya/releases/download/v0.3.0/fya_0.3.0_linux_arm64.tar.gz"
      sha256 "e0888233c5acaeb3166a02c52686f4e4f8d66a1c16d2b0a651485126fe43f055"
      define_method(:install) do
        bin.install "fya"
      end
    end
  end

  test do
    system "#{bin}/fya", "--version"
  end
end
