# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fya < Formula
  desc "Claude Code print-mode wrapper backed by an interactive PTY session"
  homepage "https://github.com/umputun/fya"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/fya/releases/download/v0.2.1/fya_0.2.1_darwin_amd64.tar.gz"
      sha256 "0e045cd86a1ce7cf96010bb481628e5dabef70069dc100512f723a2ff1af79c3"

      define_method(:install) do
        bin.install "fya"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/fya/releases/download/v0.2.1/fya_0.2.1_darwin_arm64.tar.gz"
      sha256 "a8165a94bb53aa5a8506624bea13f5db894db5a268a164b989b45c37b6155245"

      define_method(:install) do
        bin.install "fya"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/fya/releases/download/v0.2.1/fya_0.2.1_linux_amd64.tar.gz"
      sha256 "89088b22985b24d29b4903c6d3a43b7a54dd65541364b81ac7943f35a1e6501a"
      define_method(:install) do
        bin.install "fya"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/fya/releases/download/v0.2.1/fya_0.2.1_linux_arm64.tar.gz"
      sha256 "b5e4229b48e69322d49970f0a7a200583f0ec6902e41a9468f09075f694874e3"
      define_method(:install) do
        bin.install "fya"
      end
    end
  end

  test do
    system "#{bin}/fya", "--version"
  end
end
