# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LocalDocsMcp < Formula
  desc "MCP server for local documentation access"
  homepage "https://github.com/umputun/local-docs-mcp"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.2.0/local-docs-mcp_v0.2.0_macos_x86_64.tar.gz"
      sha256 "4ed7fd42092b4dff7caf78f350b55cdf5d7f5a4beaa243905b0051c9789dac01"

      def install
        bin.install "local-docs-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.2.0/local-docs-mcp_v0.2.0_macos_arm64.tar.gz"
      sha256 "58bda1ec9f8ae8a78af4d7b1995043bfeb1b41d79b6298e1e0f0f9b00c3acf59"

      def install
        bin.install "local-docs-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.2.0/local-docs-mcp_v0.2.0_linux_x86_64.tar.gz"
      sha256 "68181d6c3f661ebe7a31eeefe6d6951f26a6655f96326a11e1e4600063514c87"

      def install
        bin.install "local-docs-mcp"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.2.0/local-docs-mcp_v0.2.0_linux_arm.tar.gz"
      sha256 "ff33ebc53b4d16a2f36f0dbd99fa947b3a169002b8030e534cafbbca2a0336e3"

      def install
        bin.install "local-docs-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/local-docs-mcp/releases/download/v0.2.0/local-docs-mcp_v0.2.0_linux_arm64.tar.gz"
      sha256 "9fddebcf097e495810cf6981b4bf6834e9e3759571a165c293db5858e9ab6cdf"

      def install
        bin.install "local-docs-mcp"
      end
    end
  end
end
