# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ralphex < Formula
  desc "Autonomous plan execution with Claude Code"
  homepage "https://github.com/umputun/ralphex"
  version "0.15.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/ralphex/releases/download/v0.15.1/ralphex_0.15.1_darwin_amd64.tar.gz"
      sha256 "1c0169a2d8a2847e96639876d1f15f5abc44b6a5dafbd416ec656d4a517165c4"

      def install
        bin.install "ralphex"
        bash_completion.install "completions/ralphex.bash" => "ralphex"
        zsh_completion.install "completions/ralphex.zsh" => "_ralphex"
        fish_completion.install "completions/ralphex.fish" => "ralphex.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/ralphex/releases/download/v0.15.1/ralphex_0.15.1_darwin_arm64.tar.gz"
      sha256 "038596df746da7f71a0a7fc0eea065378590a361167ae4835bd0e6ecffed30bf"

      def install
        bin.install "ralphex"
        bash_completion.install "completions/ralphex.bash" => "ralphex"
        zsh_completion.install "completions/ralphex.zsh" => "_ralphex"
        fish_completion.install "completions/ralphex.fish" => "ralphex.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/ralphex/releases/download/v0.15.1/ralphex_0.15.1_linux_amd64.tar.gz"
      sha256 "f76a47a1693d9fe5397c8b07c78f604455ffab8d2cd190fcc2f5f04e65ce9f75"
      def install
        bin.install "ralphex"
        bash_completion.install "completions/ralphex.bash" => "ralphex"
        zsh_completion.install "completions/ralphex.zsh" => "_ralphex"
        fish_completion.install "completions/ralphex.fish" => "ralphex.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/ralphex/releases/download/v0.15.1/ralphex_0.15.1_linux_arm64.tar.gz"
      sha256 "72211712ee9c157993a1ffefcb2394947aa9b8b56a489115d20e6e2195989892"
      def install
        bin.install "ralphex"
        bash_completion.install "completions/ralphex.bash" => "ralphex"
        zsh_completion.install "completions/ralphex.zsh" => "_ralphex"
        fish_completion.install "completions/ralphex.fish" => "ralphex.fish"
      end
    end
  end
end
