# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reproxy < Formula
  desc "Simple edge HTTP(s) reverse proxy with automatic SSL"
  homepage "https://reproxy.io"
  version "1.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/reproxy/releases/download/v1.7.0/reproxy_v1.7.0_macos_amd64.tar.gz"
      sha256 "f608f2f908c8787fd64fb7980a12cdb645ff7d9867958f6f3de51524bef71cf2"

      def install
        bin.install "reproxy"
        bash_completion.install "completions/reproxy.bash" => "reproxy"
        zsh_completion.install "completions/reproxy.zsh" => "_reproxy"
        fish_completion.install "completions/reproxy.fish" => "reproxy.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/reproxy/releases/download/v1.7.0/reproxy_v1.7.0_macos_arm64.tar.gz"
      sha256 "77d683afc7a98e739640f05a34c32118ae68989878c9d4b11d4112fb7d83159c"

      def install
        bin.install "reproxy"
        bash_completion.install "completions/reproxy.bash" => "reproxy"
        zsh_completion.install "completions/reproxy.zsh" => "_reproxy"
        fish_completion.install "completions/reproxy.fish" => "reproxy.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/reproxy/releases/download/v1.7.0/reproxy_v1.7.0_linux_amd64.tar.gz"
      sha256 "091544d49e6b2b1f8c68d5dfe812960430aa473231f9872966ab0efcda4866b8"

      def install
        bin.install "reproxy"
        bash_completion.install "completions/reproxy.bash" => "reproxy"
        zsh_completion.install "completions/reproxy.zsh" => "_reproxy"
        fish_completion.install "completions/reproxy.fish" => "reproxy.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/reproxy/releases/download/v1.7.0/reproxy_v1.7.0_linux_arm64.tar.gz"
      sha256 "7bedecbee091c6cbf4dd6c71491027412035731159aeebdc955734cbf4ec1628"

      def install
        bin.install "reproxy"
        bash_completion.install "completions/reproxy.bash" => "reproxy"
        zsh_completion.install "completions/reproxy.zsh" => "_reproxy"
        fish_completion.install "completions/reproxy.fish" => "reproxy.fish"
      end
    end
  end
end
