# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Reproxy < Formula
  desc "Simple edge HTTP(s) reverse proxy with automatic SSL"
  homepage "https://reproxy.io"
  version "1.6.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/reproxy/releases/download/v1.6.0/reproxy_v1.6.0_macos_amd64.tar.gz"
      sha256 "55ee2ca04104a31a975e4b93d9a9b5f45c62b9604fc250ff56d91fe412af1552"

      def install
        bin.install "reproxy"
        bash_completion.install "completions/reproxy.bash" => "reproxy"
        zsh_completion.install "completions/reproxy.zsh" => "_reproxy"
        fish_completion.install "completions/reproxy.fish" => "reproxy.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/reproxy/releases/download/v1.6.0/reproxy_v1.6.0_macos_arm64.tar.gz"
      sha256 "8dc5eb8bcd25c6f95a24cfe832fb44e724973bb1c64fc697e78a73ba0e7f97ab"

      def install
        bin.install "reproxy"
        bash_completion.install "completions/reproxy.bash" => "reproxy"
        zsh_completion.install "completions/reproxy.zsh" => "_reproxy"
        fish_completion.install "completions/reproxy.fish" => "reproxy.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/reproxy/releases/download/v1.6.0/reproxy_v1.6.0_linux_amd64.tar.gz"
      sha256 "92c911d47f188cc7967a4f99c1463062ffca5644517ac8aa8f5157c3162c62db"

      def install
        bin.install "reproxy"
        bash_completion.install "completions/reproxy.bash" => "reproxy"
        zsh_completion.install "completions/reproxy.zsh" => "_reproxy"
        fish_completion.install "completions/reproxy.fish" => "reproxy.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/reproxy/releases/download/v1.6.0/reproxy_v1.6.0_linux_arm64.tar.gz"
      sha256 "8886f620ae53750b9303b625878c1a0f26575d2bf47d143e66178be0a4d1b5fe"

      def install
        bin.install "reproxy"
        bash_completion.install "completions/reproxy.bash" => "reproxy"
        zsh_completion.install "completions/reproxy.zsh" => "_reproxy"
        fish_completion.install "completions/reproxy.fish" => "reproxy.fish"
      end
    end
  end
end
