# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revdiff < Formula
  desc "TUI diff viewer with inline annotations"
  homepage "https://github.com/umputun/revdiff"
  version "0.7.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/revdiff/releases/download/v0.7.2/revdiff_0.7.2_darwin_amd64.tar.gz"
      sha256 "18f6671a68116c8f1bce28fba879a42c374600ed32f23a08cdda31b2ae6738e6"

      define_method(:install) do
        bin.install "revdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/revdiff/releases/download/v0.7.2/revdiff_0.7.2_darwin_arm64.tar.gz"
      sha256 "bbac004eb84cfb0d7fe32d2d5f23fc0a249eaa8d0ae6ff053818b940f7d9eb4a"

      define_method(:install) do
        bin.install "revdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/revdiff/releases/download/v0.7.2/revdiff_0.7.2_linux_amd64.tar.gz"
      sha256 "8b5c65fbdacad40c6cac84689b4bfdaa20173bc4589e46d08b2b6c89f04d919d"
      define_method(:install) do
        bin.install "revdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/revdiff/releases/download/v0.7.2/revdiff_0.7.2_linux_arm64.tar.gz"
      sha256 "2b67ca890b6c0d1a25336907aa9eb2732c49593e5cbb2185acf5a9f768e10148"
      define_method(:install) do
        bin.install "revdiff"
      end
    end
  end
end
