# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Revdiff < Formula
  desc "TUI for reviewing diffs, files, and documents with inline annotations"
  homepage "https://github.com/umputun/revdiff"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/revdiff/releases/download/v0.13.0/revdiff_0.13.0_darwin_amd64.tar.gz"
      sha256 "89fec24aafbfe3dcd0b98cde127995597334b88050d5e5679990b1465dca4f38"

      define_method(:install) do
        bin.install "revdiff"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/revdiff/releases/download/v0.13.0/revdiff_0.13.0_darwin_arm64.tar.gz"
      sha256 "b68a7aeea764e481c8bdfdca13600599d194bba9c3c3fafc9e3d1353c7516243"

      define_method(:install) do
        bin.install "revdiff"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/revdiff/releases/download/v0.13.0/revdiff_0.13.0_linux_amd64.tar.gz"
      sha256 "3981a9a3ce0e624135fa0c5ce655560d94d9f33449064c0cda26e37e5a6c502e"
      define_method(:install) do
        bin.install "revdiff"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/revdiff/releases/download/v0.13.0/revdiff_0.13.0_linux_arm64.tar.gz"
      sha256 "efcfa9487a3c546ae1979bed58fb60edee071f38e629ee2c3b6f24bd4451f408"
      define_method(:install) do
        bin.install "revdiff"
      end
    end
  end
end
