# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Secrets < Formula
  desc "Self-hosted service for sharing encrypted secrets with one-time access"
  homepage "https://github.com/umputun/secrets"
  version "2.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/secrets/releases/download/v2.2.6/secrets_v2.2.6_macos_x86_64.tar.gz"
      sha256 "1507dc4523fe20da6eab7f342b0cc1831714500aa994949add10d8e14ef52107"

      def install
        bin.install "secrets"
        bash_completion.install "completions/secrets.bash" => "secrets"
        zsh_completion.install "completions/secrets.zsh" => "_secrets"
        fish_completion.install "completions/secrets.fish" => "secrets.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/secrets/releases/download/v2.2.6/secrets_v2.2.6_macos_arm64.tar.gz"
      sha256 "d255ddd133d821ceaaff73e7c658b492ac3072ac701540bde1a460a5c9a3121d"

      def install
        bin.install "secrets"
        bash_completion.install "completions/secrets.bash" => "secrets"
        zsh_completion.install "completions/secrets.zsh" => "_secrets"
        fish_completion.install "completions/secrets.fish" => "secrets.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/secrets/releases/download/v2.2.6/secrets_v2.2.6_linux_x86_64.tar.gz"
      sha256 "404fb4ae401c298c6a1bc33c3087bf2698c08a95da40ddae45e91b1ea6ee8577"

      def install
        bin.install "secrets"
        bash_completion.install "completions/secrets.bash" => "secrets"
        zsh_completion.install "completions/secrets.zsh" => "_secrets"
        fish_completion.install "completions/secrets.fish" => "secrets.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/secrets/releases/download/v2.2.6/secrets_v2.2.6_linux_arm.tar.gz"
      sha256 "8a96b460952f11e783c1dd80b27316c6f2b0cf4e689503cd70abc2e1c7ab3503"

      def install
        bin.install "secrets"
        bash_completion.install "completions/secrets.bash" => "secrets"
        zsh_completion.install "completions/secrets.zsh" => "_secrets"
        fish_completion.install "completions/secrets.fish" => "secrets.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/secrets/releases/download/v2.2.6/secrets_v2.2.6_linux_arm64.tar.gz"
      sha256 "9cef159cdb6b035f32f3e661b2648d1f2d62074f2897d7da07daa32cd878945c"

      def install
        bin.install "secrets"
        bash_completion.install "completions/secrets.bash" => "secrets"
        zsh_completion.install "completions/secrets.zsh" => "_secrets"
        fish_completion.install "completions/secrets.fish" => "secrets.fish"
      end
    end
  end
end
