# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spot < Formula
  desc "Spot (aka simplotask) is a powerful and easy-to-use tool for effortless deployment and configuration management."
  homepage "https://spot.umputun.dev/"
  version "1.19.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/spot/releases/download/v1.19.3/spot_v1.19.3_macos_x86_64.tar.gz"
      sha256 "b5ca4a72b4087b349c13e5c0e62b1e046c79927897e9aba7d6be4729c7b974f8"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/spot/releases/download/v1.19.3/spot_v1.19.3_macos_arm64.tar.gz"
      sha256 "60ac5f7e4d6571820eac136fe56af1ae898b9f5a3ee323460dcdc5c8642368d9"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.19.3/spot_v1.19.3_linux_x86_64.tar.gz"
      sha256 "f9c5847a49324d80e31b0c035886eec4ee2bfa6fd0b38e1a590481e90ad171b3"
      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.19.3/spot_v1.19.3_linux_arm.tar.gz"
      sha256 "68728eded8b9afbbf9d85cfe9a7735569cf35ea6c4b39a9b5f0f5df77bb87bd3"
      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.19.3/spot_v1.19.3_linux_arm64.tar.gz"
      sha256 "9a0b8643d4aa7c98dadce2132121cf191d1e0bb5836001949b7fb499a86c38c7"
      def install
        bin.install "spot"
        bin.install "spot-secrets"
      end
    end
  end
end
