# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spot < Formula
  desc "Spot (aka spotctl) is a powerful and easy-to-use tool for effortless deployment and configuration management."
  homepage "https://spotctl.com/"
  version "1.20.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/spot/releases/download/v1.20.1/spot_v1.20.1_macos_x86_64.tar.gz"
      sha256 "6312977cef69c8dc28bbdf13f948d3465b817fef3aac45c9e47c49f89f668c2f"

      define_method(:install) do
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/spot/releases/download/v1.20.1/spot_v1.20.1_macos_arm64.tar.gz"
      sha256 "249f09c41acb567bbae0c3caa9ff2e4449a10f91953fbc8b4b08127c70285ebf"

      define_method(:install) do
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.20.1/spot_v1.20.1_linux_x86_64.tar.gz"
      sha256 "5c57fa7e9ab8d402634b23c73d8c6a21207f1218a77f815b130c9d0380e6539e"
      define_method(:install) do
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.20.1/spot_v1.20.1_linux_arm.tar.gz"
      sha256 "95b3077f9565c17fa06ff281bd8e826d5509d0f46c8ee6216723ef603093aa1b"
      define_method(:install) do
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.20.1/spot_v1.20.1_linux_arm64.tar.gz"
      sha256 "56085c7b5fd3c6efa27bc48c8e890d31856b8bb4cc951bcf01bd76c1c669d7d2"
      define_method(:install) do
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
  end
end
