# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spot < Formula
  desc "Spot (aka spotctl) is a powerful and easy-to-use tool for effortless deployment and configuration management."
  homepage "https://spotctl.com/"
  version "1.20.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/spot/releases/download/v1.20.0/spot_v1.20.0_macos_x86_64.tar.gz"
      sha256 "ed3329c87828d67ab3b58fda1910bca6f771c0d35a5cc23ae7eca1434136d415"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/spot/releases/download/v1.20.0/spot_v1.20.0_macos_arm64.tar.gz"
      sha256 "f441a7c556cff407b9e385717594a31083e24e49c9deb22629a5528655b94899"

      def install
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.20.0/spot_v1.20.0_linux_x86_64.tar.gz"
      sha256 "129eaff385fba885303bf74c1670ac55266ae46d98b1658f4c8e33a6f9dcce47"
      def install
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.20.0/spot_v1.20.0_linux_arm.tar.gz"
      sha256 "c1d52283f9b7e5a7557105d560f701a8a7de0f0f7113104783c088cdabff45c0"
      def install
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/spot/releases/download/v1.20.0/spot_v1.20.0_linux_arm64.tar.gz"
      sha256 "0241b46376d973a5048e61ef0044d4d8795176b6c8adfa3f8e437e5500c27e69"
      def install
        bin.install "spot"
        bin.install "spot-secrets"
        bash_completion.install "completions/spot.bash" => "spot"
        bash_completion.install "completions/spot-secrets.bash" => "spot-secrets"
        zsh_completion.install "completions/spot.zsh" => "_spot"
        zsh_completion.install "completions/spot-secrets.zsh" => "_spot-secrets"
        fish_completion.install "completions/spot.fish" => "spot.fish"
        fish_completion.install "completions/spot-secrets.fish" => "spot-secrets.fish"
      end
    end
  end
end
