# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Lightweight key-value configuration service for centralized config management"
  homepage "https://github.com/umputun/stash"
  version "0.21.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.21.0/stash_v0.21.0_macos_x86_64.tar.gz"
      sha256 "69314300f668045a3a4eef2c7ce117c848142dec2b40194f71fe97db220226fb"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/stash/releases/download/v0.21.0/stash_v0.21.0_macos_arm64.tar.gz"
      sha256 "95f591a1408f45d03179ca81669670d9021f9868900e1e3a4749dc46d0161129"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.21.0/stash_v0.21.0_linux_x86_64.tar.gz"
      sha256 "798adca79bc5db15a9d098acf5397afe86aa37519597b6fa476a4ad4f1999f7d"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.21.0/stash_v0.21.0_linux_arm.tar.gz"
      sha256 "465df791c26858c6a8029729178f558b52f805790990ecc2bdc2ef3492fd5270"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.21.0/stash_v0.21.0_linux_arm64.tar.gz"
      sha256 "14bdba8053b1a2d7ec4e7fbc59206ef998c9598fd67150b86fcb14ad302bb0c0"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
  end
end
