# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stash < Formula
  desc "Lightweight key-value configuration service for centralized config management"
  homepage "https://github.com/umputun/stash"
  version "0.20.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.20.0/stash_v0.20.0_macos_x86_64.tar.gz"
      sha256 "fc94da1e8db15aaf5fdacfce2a316c4a753b8f4851aeb163612104fa7b70a655"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/stash/releases/download/v0.20.0/stash_v0.20.0_macos_arm64.tar.gz"
      sha256 "6560cc76215e23c0de3aa55fe5a8b799e94067e2a431a270b2681605c7642a0f"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/stash/releases/download/v0.20.0/stash_v0.20.0_linux_x86_64.tar.gz"
      sha256 "6352f5900720459b91d33b82d6d131dc2fb5b9dc4297e89db8367090e7aa6cb9"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.20.0/stash_v0.20.0_linux_arm.tar.gz"
      sha256 "ca7edbb02418a8656e21cb182c5986e25029ed18edef5ff978a1d85b43e22837"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/stash/releases/download/v0.20.0/stash_v0.20.0_linux_arm64.tar.gz"
      sha256 "905459be6f7fc9ec32bbc98a237d7df34eb6b33e39be23c7690ea0275bc8daa1"

      def install
        bin.install "stash"
        bash_completion.install "completions/stash.bash" => "stash"
        zsh_completion.install "completions/stash.zsh" => "_stash"
        fish_completion.install "completions/stash.fish" => "stash.fish"
      end
    end
  end
end
