# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SysAgent < Formula
  desc "SysAgent is a simple service reporting server status via HTTP GET request. It is useful for monitoring and debugging purposes, but usually used as a part of some other monitoring system collecting data and serving it."
  homepage "https://sys-agent.umputun.dev"
  version "1.7.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/sys-agent/releases/download/v1.7.1/sys-agent_v1.7.1_macos_x86_64.tar.gz"
      sha256 "72941ed8f1b70e00822f4d9f4c329ccec168fba358f98d060dd958d2bfd428f0"

      def install
        bin.install "sys-agent"
        bash_completion.install "completions/sys-agent.bash" => "sys-agent"
        zsh_completion.install "completions/sys-agent.zsh" => "_sys-agent"
        fish_completion.install "completions/sys-agent.fish" => "sys-agent.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/sys-agent/releases/download/v1.7.1/sys-agent_v1.7.1_macos_arm64.tar.gz"
      sha256 "e5933d2f8bef0b4489d2d3e3db3a37738d219d636c912c5ea283d63a903517fe"

      def install
        bin.install "sys-agent"
        bash_completion.install "completions/sys-agent.bash" => "sys-agent"
        zsh_completion.install "completions/sys-agent.zsh" => "_sys-agent"
        fish_completion.install "completions/sys-agent.fish" => "sys-agent.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/sys-agent/releases/download/v1.7.1/sys-agent_v1.7.1_linux_x86_64.tar.gz"
      sha256 "fac61330e2dde25210706284279fc9314ff5ee0855de6d484ad268743eaa517b"

      def install
        bin.install "sys-agent"
        bash_completion.install "completions/sys-agent.bash" => "sys-agent"
        zsh_completion.install "completions/sys-agent.zsh" => "_sys-agent"
        fish_completion.install "completions/sys-agent.fish" => "sys-agent.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/sys-agent/releases/download/v1.7.1/sys-agent_v1.7.1_linux_arm.tar.gz"
      sha256 "9418ac927ec1e79303f41d69190bbbcafd3ff1327d67620b64c1cb11e46ddbc4"

      def install
        bin.install "sys-agent"
        bash_completion.install "completions/sys-agent.bash" => "sys-agent"
        zsh_completion.install "completions/sys-agent.zsh" => "_sys-agent"
        fish_completion.install "completions/sys-agent.fish" => "sys-agent.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/sys-agent/releases/download/v1.7.1/sys-agent_v1.7.1_linux_arm64.tar.gz"
      sha256 "e95eabe31b0cb5ca1db1b35be79615f2e59d6253274f6172f3ef6f5de9acb772"

      def install
        bin.install "sys-agent"
        bash_completion.install "completions/sys-agent.bash" => "sys-agent"
        zsh_completion.install "completions/sys-agent.zsh" => "_sys-agent"
        fish_completion.install "completions/sys-agent.fish" => "sys-agent.fish"
      end
    end
  end
end
