# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TgSpam < Formula
  desc "tg-spam is a self-hosted Telegram bot fighting spam like no tomorrow."
  homepage "https://tg-spam.umputun.dev"
  version "1.25.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/tg-spam/releases/download/v1.25.0/tg-spam_v1.25.0_macos_x86_64.tar.gz"
      sha256 "d0ff4ad3b23d4bd3b70962b791907ba102e0d712321368679887db31f788ab85"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/tg-spam/releases/download/v1.25.0/tg-spam_v1.25.0_macos_arm64.tar.gz"
      sha256 "aa891e876398f32ff4c94b28f1708e8cca0ea9abe6a3808fcf4cf90503af4c3a"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/tg-spam/releases/download/v1.25.0/tg-spam_v1.25.0_linux_x86_64.tar.gz"
      sha256 "d3a33865a7cde48a130cc6eb59afaeb439b0a4db2d86346178156acef96acba4"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/tg-spam/releases/download/v1.25.0/tg-spam_v1.25.0_linux_arm.tar.gz"
      sha256 "985021288afb55d6e880b2577fce12a53ed3eb387d0a8ef6eef46f9636f3888a"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/tg-spam/releases/download/v1.25.0/tg-spam_v1.25.0_linux_arm64.tar.gz"
      sha256 "4f7f6b27487b1e8cff1f224fc73015b948943f0d1e2fbc3264551a5a2481f65c"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
  end
end
