# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TgSpam < Formula
  desc "tg-spam is a self-hosted Telegram bot fighting spam like no tomorrow."
  homepage "https://tg-spam.umputun.dev"
  version "1.23.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/tg-spam/releases/download/v1.23.7/tg-spam_v1.23.7_macos_x86_64.tar.gz"
      sha256 "ec7420334ff01ef0bed3ca0172a5e77a77a0c9b864fb81357e73e974ad8a47b8"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/tg-spam/releases/download/v1.23.7/tg-spam_v1.23.7_macos_arm64.tar.gz"
      sha256 "294ff226f9f8387d358959cd8af6aed0a065d8e9f7a43c56c21b120c97cfade3"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/tg-spam/releases/download/v1.23.7/tg-spam_v1.23.7_linux_x86_64.tar.gz"
      sha256 "05f642c9b287ee33e45cda3897d52ce6caadfe1e802d977262cb85ed415ff045"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/tg-spam/releases/download/v1.23.7/tg-spam_v1.23.7_linux_arm.tar.gz"
      sha256 "0fffad4dd4303ff4199a8a9517ca6620a57fc6eee31ce81c37a15dab827b79b4"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/tg-spam/releases/download/v1.23.7/tg-spam_v1.23.7_linux_arm64.tar.gz"
      sha256 "75ca78c71dfe3c8870026d9fea3493e2737cb8876843f9169fde03104b000cc4"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
  end
end
