# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TgSpam < Formula
  desc "tg-spam is a self-hosted Telegram bot fighting spam like no tomorrow."
  homepage "https://tg-spam.umputun.dev"
  version "1.24.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/tg-spam/releases/download/v1.24.0/tg-spam_v1.24.0_macos_x86_64.tar.gz"
      sha256 "9c89b3aa3af2a1bbff9c1c20e69f7ed2b3e5a8f2443d46b0639a1dcda65b7ac5"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/tg-spam/releases/download/v1.24.0/tg-spam_v1.24.0_macos_arm64.tar.gz"
      sha256 "1a93dac71ed7b0557f15e81cdb2645eff91bc968c4abde93d423f8eac8a883c8"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/tg-spam/releases/download/v1.24.0/tg-spam_v1.24.0_linux_x86_64.tar.gz"
      sha256 "eb48b72e0c0ce7bc2fedf1befef6b9b07e8ab14f5354eacccff7201bbdc5a405"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/tg-spam/releases/download/v1.24.0/tg-spam_v1.24.0_linux_arm.tar.gz"
      sha256 "06c9ab631123704878cd6ba8f24ce4028f46b62b96ef3825de378b94a559f965"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/tg-spam/releases/download/v1.24.0/tg-spam_v1.24.0_linux_arm64.tar.gz"
      sha256 "d9235b957749ff7cff2fedc822511174ff4eb1cbfe8be922497164ab357966d5"

      def install
        bin.install "tg-spam"
        bash_completion.install "completions/tg-spam.bash" => "tg-spam"
        zsh_completion.install "completions/tg-spam.zsh" => "_tg-spam"
        fish_completion.install "completions/tg-spam.fish" => "tg-spam.fish"
      end
    end
  end
end
