# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class UnfuckAiComments < Formula
  desc "unfuck-ai-comments is a tool that converts all comments inside Go functions to lowercase"
  homepage "https://unfuck-ai-comments.umputun.dev"
  version "0.9.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.9.3/unfuck-ai-comments_v0.9.3_macos_x86_64.tar.gz"
      sha256 "47303e6cb52adbf5deecea994d696702e89d72fb5e012945eedef5937f6869fc"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.9.3/unfuck-ai-comments_v0.9.3_macos_arm64.tar.gz"
      sha256 "7bc3177cee075dc9565df3f8bc07c9b3b2aa41519ddc82a127b9c065a46c0486"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.9.3/unfuck-ai-comments_v0.9.3_linux_x86_64.tar.gz"
      sha256 "ca89627963e4da90fe4e95af70a0afb6dfb26cc4b8619cbd0d7d1743522ce482"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.9.3/unfuck-ai-comments_v0.9.3_linux_arm.tar.gz"
      sha256 "3dfd36e8dd8271851eda4eb6883754d1fba8c061d42ecf0c764c6c2175c2c5ff"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/unfuck-ai-comments/releases/download/v0.9.3/unfuck-ai-comments_v0.9.3_linux_arm64.tar.gz"
      sha256 "0616701cc9c9092ab7801e49713453caa75da547422fec11bb7807c356fcd2d6"

      def install
        bin.install "unfuck-ai-comments"
      end
    end
  end
end
