# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weblist < Formula
  desc "weblist is a self-hosted web service to access local files and folders"
  homepage "https://weblist.umputun.dev"
  version "0.17.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.17.1/weblist_v0.17.1_macos_x86_64.tar.gz"
      sha256 "7fb78127293cc055d710af76ca36c9a06acc159a0cc5287720a46e736489ef11"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/weblist/releases/download/v0.17.1/weblist_v0.17.1_macos_arm64.tar.gz"
      sha256 "4d9d5b3bb66d747e1397b075cddc48a91ec8b283b48ee3d0f2a0b879a57d3c3e"

      def install
        bin.install "weblist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.17.1/weblist_v0.17.1_linux_x86_64.tar.gz"
      sha256 "e798d77d7a77787c0ca932c0603df1f8753c493f413556e24de276392808acf5"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.17.1/weblist_v0.17.1_linux_arm.tar.gz"
      sha256 "69c16f5a8b002287bddaeae9251c469157216c2f4915b746be5506f629f959e3"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.17.1/weblist_v0.17.1_linux_arm64.tar.gz"
      sha256 "f7713273abccff5fc7e832eb06126ee8c0f066fc9613c81a3497302ff719d999"

      def install
        bin.install "weblist"
      end
    end
  end
end
