# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weblist < Formula
  desc "weblist is a self-hosted web service to access local files and folders"
  homepage "https://weblist.umputun.dev"
  version "0.19.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.19.2/weblist_v0.19.2_macos_x86_64.tar.gz"
      sha256 "98e3d8a8919116bf1ba2094db8105ed3738093bcbfccecea1ee40bb9bb88e5ff"

      def install
        bin.install "weblist"
        bash_completion.install "completions/weblist.bash" => "weblist"
        zsh_completion.install "completions/weblist.zsh" => "_weblist"
        fish_completion.install "completions/weblist.fish" => "weblist.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/weblist/releases/download/v0.19.2/weblist_v0.19.2_macos_arm64.tar.gz"
      sha256 "ce2089d67a88ecfc87019a3b8134a638f1ed566061c8cb2875008ccedf7ccc93"

      def install
        bin.install "weblist"
        bash_completion.install "completions/weblist.bash" => "weblist"
        zsh_completion.install "completions/weblist.zsh" => "_weblist"
        fish_completion.install "completions/weblist.fish" => "weblist.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.19.2/weblist_v0.19.2_linux_x86_64.tar.gz"
      sha256 "1e383c89d4051f3e6a8a06af5de90c6d6e9bde58e5a71fa45185cfcc117163a9"

      def install
        bin.install "weblist"
        bash_completion.install "completions/weblist.bash" => "weblist"
        zsh_completion.install "completions/weblist.zsh" => "_weblist"
        fish_completion.install "completions/weblist.fish" => "weblist.fish"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.19.2/weblist_v0.19.2_linux_arm.tar.gz"
      sha256 "565ec637b866e9fadd300e4e3541213826639ccf7d40baad607eefcdf70f96be"

      def install
        bin.install "weblist"
        bash_completion.install "completions/weblist.bash" => "weblist"
        zsh_completion.install "completions/weblist.zsh" => "_weblist"
        fish_completion.install "completions/weblist.fish" => "weblist.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.19.2/weblist_v0.19.2_linux_arm64.tar.gz"
      sha256 "edbf440ab00f490f3a8822593f4b64803fe0eb5008eb561ac6e949f105edc0e4"

      def install
        bin.install "weblist"
        bash_completion.install "completions/weblist.bash" => "weblist"
        zsh_completion.install "completions/weblist.zsh" => "_weblist"
        fish_completion.install "completions/weblist.fish" => "weblist.fish"
      end
    end
  end
end
