# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Weblist < Formula
  desc "weblist is a self-hosted web service to access local files and folders"
  homepage "https://weblist.umputun.dev"
  version "0.17.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.17.2/weblist_v0.17.2_macos_x86_64.tar.gz"
      sha256 "68b81bb03ae2de14392e95f59b8e5af4f406ef34daefdb0a47c4a5e701efd938"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/umputun/weblist/releases/download/v0.17.2/weblist_v0.17.2_macos_arm64.tar.gz"
      sha256 "81cd235b37413a044bed2326960b74756ae030536286322b52687fcd6a618580"

      def install
        bin.install "weblist"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/umputun/weblist/releases/download/v0.17.2/weblist_v0.17.2_linux_x86_64.tar.gz"
      sha256 "125520f79926780515bd5c877f785447dae2153fbfba7e28920e5d32426275c2"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.17.2/weblist_v0.17.2_linux_arm.tar.gz"
      sha256 "9f6f007de51970c1ef09269f686e154a01c3fc8336e91e46490bb53fa84f37fc"

      def install
        bin.install "weblist"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/umputun/weblist/releases/download/v0.17.2/weblist_v0.17.2_linux_arm64.tar.gz"
      sha256 "c2f22f2addc5b4674f997d5c8298a3f10d9a63a2a1aebb7db006b42e92fb2115"

      def install
        bin.install "weblist"
      end
    end
  end
end
